basic_settings:
  site_title: M. KAISER
  favicon_image: /images/favicon.png

header_settings:
  logo_image: /images/mkaiser.png
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'PROJECTS'
      url: '/'
    - title: 'ABOUT'
      url: '/about'
    - title: 'CONTACT'
      url: '/contact'

footer_settings:
  footer_tagline: M. KAISER | BUILDING + REMODELING

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 20
  content_alignment: bottom

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Website Submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: 'https://www.facebook.com/kaiser.building/'
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: 'https://www.linkedin.com/in/michaelkaiser165'
  houzz_url: 'https://www.houzz.com/professionals/woodworkers-and-carpenters/m-kaiser-building-and-remodeling-pfvwus-pf~1888232351'

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#000000'
  text_medium_color: '#1E272C'
  text_light_color: '#4F6571'
  accent_color: '#37517e'
  border_color: '#dddddd'
  overlay_background_color: '#37517e'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#37517e'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Poppins:300,500" rel="stylesheet">'
  title_font: '"Poppins", sans-serif'
  body_font: '"Poppins", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 14
    large_size: 15
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 24
    large_size: 28
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 13
    medium_size: 15
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 40
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: "37818525"
  custom_styles: ""
  header_js: ""
  footer_js: ""